@startuml
top to bottom direction
skinparam headerFontSize 30
skinparam headerFontStyle bold
skinparam classAttributeIconSize 0
scale 1.0
package DataBase {
class DataBase.ElentBDConnection {
.. Methods ..
+getComponentName(String) : void
+getCost(String) : void
+getDBConnection(int) : void
+getFunctinalDamageData(String) : void
+getFunctinalRiskData(String) : void
+getOperatingDuration(String) : void
+getOperatingMode(String) : void
+getProbabilityData(String) : void
+getStructureDamageData(String) : void
+getStructureRiskData(String) : void
}
class DataBase.InnerConnDBConnection {
.. Methods ..
+getComponentName(String) : void
+getCost(String) : void
+getDBConnection(int) : void
+getFunctinalDamageData(String) : void
+getFunctinalRiskData(String) : void
+getOperatingDuration(String) : void
+getOperatingMode(String) : void
+getProbabilityData(String) : void
+getStructureDamageData(String) : void
+getStructureRiskData(String) : void
}
class DataBase.OperationModes {
.. Methods ..
+getComponentName(String) : void
+getCost(String) : void
+getDBConnection(int) : void
+getFunctinalDamageData(String) : void
+getFunctinalRiskData(String) : void
+getOperatingDuration(String) : void
+getOperatingMode(String) : void
+getProbabilityData(String) : void
+getStructureDamageData(String) : void
+getStructureRiskData(String) : void
}
class DataBase.Cost {
.. Methods ..
+getComponentName(String) : void
+getCost(String) : void
+getDBConnection(int) : void
+getFunctinalDamageData(String) : void
+getFunctinalRiskData(String) : void
+getOperatingDuration(String) : void
+getOperatingMode(String) : void
+getProbabilityData(String) : void
+getStructureDamageData(String) : void
+getStructureRiskData(String) : void
}
class DataBase.OpeatingDuration {
.. Methods ..
+getComponentName(String) : void
+getCost(String) : void
+getDBConnection(int) : void
+getFunctinalDamageData(String) : void
+getFunctinalRiskData(String) : void
+getOperatingDuration(String) : void
+getOperatingMode(String) : void
+getProbabilityData(String) : void
+getStructureDamageData(String) : void
+getStructureRiskData(String) : void
}
class DataBase.StatisticsDBConnection {
.. Methods ..
+getComponentName(String) : void
+getCost(String) : void
+getDBConnection(int) : void
+getFunctinalDamageData(String) : void
+getFunctinalRiskData(String) : void
+getOperatingDuration(String) : void
+getOperatingMode(String) : void
+getProbabilityData(String) : void
+getStructureDamageData(String) : void
+getStructureRiskData(String) : void
}

}
package Evaluation {
class Evaluation.InnerConnRA {
.. Methods ..
+getFunctionalRiskValue(Double, Double) : void
+getStructureRiskValue(Double, Double) : void
}
class Evaluation.ElementDA {
.. Methods ..
+getFunctionalDamageValue(Double, Double) : void
+getStructureDamageValue(Double, Double) : void
}
class Evaluation.InnerConnDA {
.. Methods ..
+getFunctionalDamageValue(Double, Double) : void
+getStructureDamageValue(Double, Double) : void
}
class Evaluation.ElementRA {
.. Methods ..
+getFunctionalRiskValue(Double, Double) : void
+getStructureRiskValue(Double, Double) : void
}
class Evaluation.Probability {
.. Methods ..
+getComponentName(String) : void
+getCost(String) : void
+getFunctinalDamageData(String) : void
+getFunctinalRiskData(String) : void
+getOperatingDuration(String) : void
+getOperatingMode(String) : void
+getProbabilityData(String) : void
+getStructureDamageData(String) : void
+getStructureRiskData(String) : void
}

}
package Graphics {
class Graphics.CognitiveMap {
.. Methods ..
+drawCognitiveMap() : void
+drawDiagram() : void
+drawGraph() : void
}
class Graphics.Graph {
.. Methods ..
+drawCognitiveMap() : void
+drawDiagram() : void
+drawGraph() : void
}
class Graphics.Giaram {
.. Methods ..
+drawCognitiveMap() : void
+drawDiagram() : void
+drawGraph() : void
}

}
package com.mycompany.spprfull {
package com.mycompany.spprfull.gui {
class com.mycompany.spprfull.gui.SPPR {
.. Methods ..
.. Static ..
+ {static} main() : void
}
class com.mycompany.spprfull.gui.Gui {
.. Fields  ..
-jButton2 : JButton
-jButton3 : JButton
-jCheckBox1 : JCheckBox
-jCheckBox2 : JCheckBox
-jCheckBox3 : JCheckBox
-jCheckBox4 : JCheckBox
-jComboBox1 : JComboBox
-jLabel1 : JLabel
-jLabel2 : JLabel
-jLabel3 : JLabel
-jLabel5 : JLabel
-jLabel6 : JLabel
-jLabel7 : JLabel
-jPanel2 : JPanel
-jPanel3 : JPanel
-jPanel4 : JPanel
-jPanel5 : JPanel
-jScrollPane1 : JScrollPane
-jScrollPane2 : JScrollPane
-jScrollPane3 : JScrollPane
-jTabbedPane6 : JTabbedPane
-jTable1 : JTable
-jTable3 : JTable
-jTextArea1 : JTextArea
.. Methods ..
-initComponents() : void
-jComboBox1ActionPerformed(ActionEvent) : void
.. Static ..
+ {static} main() : void
}
class com.mycompany.spprfull.gui.MakeDesicion {
.. Methods ..
+getComponentName(String) : void
+getCost(String) : void
+getDBConnection(int) : void
+getFunctinalDamageData(String) : void
+getFunctinalRiskData(String) : void
+getOperatingDuration(String) : void
+getOperatingMode(String) : void
+getProbabilityData(String) : void
+getStructureDamageData(String) : void
+getStructureRiskData(String) : void
}

}
interface com.mycompany.spprfull.Risk  {
.. Methods ..
+ {abstract} getFunctionalRiskValue(Double, Double) : void
+ {abstract} getStructureRiskValue(Double, Double) : void
}
interface com.mycompany.spprfull.Damage  {
.. Methods ..
+ {abstract} getFunctionalDamageValue(Double, Double) : void
+ {abstract} getStructureDamageValue(Double, Double) : void
}
interface com.mycompany.spprfull.DataOutput  {
.. Methods ..
+ {abstract} getComponentName(String) : void
+ {abstract} getCost(String) : void
+ {abstract} getFunctinalDamageData(String) : void
+ {abstract} getFunctinalRiskData(String) : void
+ {abstract} getOperatingDuration(String) : void
+ {abstract} getOperatingMode(String) : void
+ {abstract} getProbabilityData(String) : void
+ {abstract} getStructureDamageData(String) : void
+ {abstract} getStructureRiskData(String) : void
}
interface com.mycompany.spprfull.Drawing  {
.. Methods ..
+ {abstract} drawCognitiveMap() : void
+ {abstract} drawDiagram() : void
+ {abstract} drawGraph() : void
}
interface com.mycompany.spprfull.BDConnection  {
.. Methods ..
+ {abstract} getDBConnection(int) : void
}

}
com.mycompany.spprfull.BDConnection <|.. DataBase.ElentBDConnection
com.mycompany.spprfull.DataOutput <|.. DataBase.ElentBDConnection
com.mycompany.spprfull.Risk <|.. Evaluation.InnerConnRA
com.mycompany.spprfull.BDConnection <|.. DataBase.InnerConnDBConnection
com.mycompany.spprfull.DataOutput <|.. DataBase.InnerConnDBConnection
com.mycompany.spprfull.Damage <|.. Evaluation.ElementDA
com.mycompany.spprfull.Damage <|.. Evaluation.InnerConnDA
com.mycompany.spprfull.BDConnection <|.. DataBase.OperationModes
com.mycompany.spprfull.DataOutput <|.. DataBase.OperationModes
com.mycompany.spprfull.BDConnection <|.. com.mycompany.spprfull.gui.MakeDesicion
com.mycompany.spprfull.DataOutput <|.. com.mycompany.spprfull.gui.MakeDesicion
com.mycompany.spprfull.BDConnection <|.. DataBase.Cost
com.mycompany.spprfull.DataOutput <|.. DataBase.Cost
com.mycompany.spprfull.Risk <|.. Evaluation.ElementRA
com.mycompany.spprfull.DataOutput <|.. Evaluation.Probability
com.mycompany.spprfull.BDConnection <|.. DataBase.OpeatingDuration
com.mycompany.spprfull.DataOutput <|.. DataBase.OpeatingDuration
com.mycompany.spprfull.Drawing <|.. Graphics.CognitiveMap
com.mycompany.spprfull.Drawing <|.. Graphics.Graph
com.mycompany.spprfull.BDConnection <|.. DataBase.StatisticsDBConnection
com.mycompany.spprfull.DataOutput <|.. DataBase.StatisticsDBConnection
com.mycompany.spprfull.Drawing <|.. Graphics.Giaram
@enduml
